[profile.default]
out = 'out'
libs = ['node_modules', 'lib']
cache_path = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
via_ir = true
test = 'test'
solc = '0.8.26'
fs_permissions = [
    { access = 'read', path = './out' }, 
    { access = 'read-write', path = './deploy-out' }
]
evm_version = 'cancun'
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@storyprotocol/core/=node_modules/@story-protocol/protocol-core/contracts/',
    '@storyprotocol/periphery/=node_modules/@story-protocol/protocol-periphery/contracts/',
    'erc6551/=node_modules/erc6551/',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/ds-test/src/',
    '@storyprotocol/test/=node_modules/@story-protocol/protocol-core/test/foundry/',
    '@solady/=node_modules/solady/'
]

[profile.test]
verbosity = 2

[rpc_endpoints]
story_testnet = "https://testnet.storyrpc.io"
story_mainnet = "https://story-network.rpc.caldera.xyz/http"

[etherscan]
story_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.storyscan.xyz/api" }
